import pickle
f=open("mazes.txt","wb")
f.close()
f=open("mazes.txt","ab")
l=[
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "XP     X             X  X",
    "X  XXX X  XXXXX XXXXXX  X",
    "X  X X X  X   X X       X",
    "X  X X X  X X XXX  XXX  X",
    "X  X        X X    X    X",
    "X  X  XX  XXX X XXXX    X",
    "X           X   X    XXXX",
    "X           X   X    X  X",
    "X  XXXXX  XXXXX X  XXX  X",
    "X      X  X   X X       X",
    "X      X  X   X X       X",
    "X  X XXX  X X XXXXXX XXXX",
    "X  X        X      X    X",
    "XXXX XXX  X XXXXX  XXX  X",
    "X      X  X     X  X    X",
    "X      X  X     X  X    X",
    "X  XXX X  XXXXX XXXX XXXX",
    "X  X   X        X    X  X",
    "X  XXX XXXXXX XXX    X  X",
    "X    X        X X    X  X",
    "XXX  X XXXXXX X XXX  X  X",
    "X    X      X     X     X",
    "XXXXXXXXXXXXXXXXXXXXXXXTX"]
pickle.dump(l,f)
l=[
"OOOOOOOOOOOOOOOOOOOOOOOOO",
"OP                  O   O",
"O OOOOOOOOO OOOOOOO O O O",
"O O       O       O O O O",
"O O OOOOOOOOOOO OOO OOO O",
"O O             O     O O",
"O OOOOOOOOOOOOO O OOOOO O",
"O             O O       O",
"O OOOOOOOOOOOOO OOOOO O O",
"O O                 O O O",
"O O OOOOOOOOOOOOOOO O O O",
"O O O             O O O O",
"O O OOOOO OOOOOOO O O O O",
"O O     O O     O O O O O",
"O OOOOO O O OOOOO O O O O",
"O     O   O     O O   O O",
"O OOO OOOOO OOO O O OOO O",
"O O O       O O   O O   O",
"O O OOOOO OOO OOOOOOO OOO",
"O O     O O         O   O",
"O O OOO O O OOOOO OOO OOO",
"O O O O O O O     O   O O",
"O O O O OOO O OOOOO OOO O",
"O   O       O           O",
"OOOOOOOOOOOOOOOOOOOOOOOTO",]
pickle.dump(l,f)
l1=[
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XP     X         X     X             X",
    "X XXXX X    XXXXXX XXX X XXXXXXXXX   X",
    "X X    X    X        X X         X   X",
    "X X XXXX    X        X XXXXXXXX  X   X",
    "X X X       X  XXXXX X        X  X   X",
    "X X X XXXXXXXX   X   X        X  X   X",
    "X X X X   X      X  XXX XXXXX X  X   X",
    "X X   X X X      X    X X X X X  X   X",
    "X X   X X X XXXXXXXXX X X X X    X   X",
    "X XXX X X X X       X X X X X  XXX   X",
    "X   X X X X X       X X X X X  X     X",
    "XXX X X X X X       X X X X X  X   XXX",
    "X   X X X X X       X X X X X  X     X",
    "X XXX X X X X       X X X X X  X   X X",
    "X X   X X X X       X X X X X  X   X X",
    "X X   X X X XXXX XXXX X X X X  X   X X",
    "X X X X X X    X X    X X X    X   X X",
    "X X X X X XXXX X X  XXX X XXXXXX   X X",
    "X X X   X    X X X        X        X X",
    "X X XXXXXXXXXX X XXXXXXXXXXXXXXXXXXX X",
    "X X            X                     T",
    "X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "X                                    X",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"]    
pickle.dump(l1,f)
l=[
"OOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OP          O       O     O",
"O OOO OOOOO OOO OOO O OOO O",
"O   O   O O     O   O   O O",
"OOO O O O O OOOOOOOOOOO O O",
"O   O O   O O       O   O O",
"O O OOOOO O O OOOOO O OOO O",
"O O     O O O   O O     O O",
"O OOOOO O O O O O OOOOO OOO",
"O O     O O   O O O   O   O",
"OOO O OOO O OOO O O O OOO O",
"O   O O   O   O O O O   O O",
"O OOO OOOOO OOO O O OOO OOO",
"O O   O       O O O   O   O",
"O O OOO OOOOO O O OOO OOO O",
"O O   O     O O     O   O O",
"O OOOOOOOOOOO OOOOOOO O O O",
"O O     O   O   O     O O O",
"O O OOOOO O OOO O OOOOO O O",
"O O       O   O   O O   O O",
"OOO OOOOOOOOO OOOOO O O O O",
"O   O     O   O   O   O O O",
"O OOOOOOO O OOO OOOOOOO O O",
"O         O   O     O   O O",
"O OOOOOOOOOOOOO O O OOOOO O",
"O               O O       O",
"OTOOOOOOOOOOOOOOOOOOOOOOOOO"]
pickle.dump(l,f)
l=[
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"OP      O     O       O     O",
"O OOO OOO OOO OOO OOOOO OOO O",
"O O     O O       O       O O",
"O OOOOOOO OOOOO O OOOOOOOOO O",
"O     O   O   O O       O   O",
"O O OOO OOO OOO OOOOOOO O O O",
"O O O       O     O     O O O",
"O O O O OOOOOOOOOOO OOOOO O O",
"O O O O O       O   O     O O",
"O O O O O OOOOO O OOO OOOOO O",
"O O O O O O   O O O   O   O O",
"O O OOO O O OOO O O O O O OOO",
"O O   O O O O     O O O O O O",
"OOO O O O O O OOOOO O O O O O",
"O O O O O O O   O O O   O O O",
"O O O O O O O OOO OOO OOO O O",
"O O O   O O   O   O O O     O",
"O OOO OOO OOOOO OOO O O OOO O",
"O       O     O       O O O O",
"O OOOOOOOOOOO OOOOOOO O O O O",
"O O O       O   O     O O O O",
"OOO O OOOOO O O O OOOOO O O O",
"O   O O   O   O O     O O   T",
"O O O O O OOOOO OOOOO O OOOOO",
"O O   O O     O O     O   O O",
"O OOOOO OOO OOOOO OOOOOOOOO O",
"O         O                 O",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOO"]
pickle.dump(l,f)
f.close()

'''f=open("mazes.txt","rb")
z=pickle.load(f)
print(z)
z=pickle.load(f)
print(z)
f.close()'''
